name: GitHub Classroom Workflow

on: [push]

jobs:
  build:
    permissions: write-all
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install apt dependencies
        run: |
          sudo apt-get install -y \
            libevent-dev \
            libfmt-dev \
            libgtest-dev \
            libprotobuf-dev \
            libpthread-stubs0-dev \
            librocksdb-dev \
            protobuf-compiler \
            zlib1g-dev

      - name: Install python dependencies
        run: |
          sudo pip3 install \
            psutil

      - uses: education/autograding@v1